'use server'

import { createClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";

export type ActionState = {
    success: boolean;
    error?: string;
    data?: any;
};

export async function createStudent(formData: FormData): Promise<ActionState> {
    const supabase = await createClient();

    // Get the current user
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
        return { success: false, error: 'No autenticado' };
    }

    // Get user's membership to determine school/owner
    const { data: membership } = await supabase
        .from('memberships')
        .select('school_id, owner_id, location_id')
        .eq('user_id', user.id)
        .single();

    if (!membership) {
        return { success: false, error: 'No se encontró la membresía del usuario' };
    }

    const data = {
        school_id: membership.school_id,
        owner_id: membership.owner_id,
        location_id: membership.location_id,
        first_name: formData.get("first_name") as string,
        last_name: formData.get("last_name") as string,
        email: formData.get("email") as string,
        phone: formData.get("phone") as string,
        dni: formData.get("dni") as string,
        address: formData.get("address") as string,
        has_license: formData.get("has_license") === 'true',
        disability_observation: formData.get("disability_observation") as string,
        emergency_contact_name: formData.get("emergency_contact_name") as string,
        emergency_contact_phone: formData.get("emergency_contact_phone") as string,
        emergency_contact_relation: formData.get("emergency_contact_relation") as string,
        gender: formData.get("gender") as string,
        status: (formData.get("status") as string) || 'active',
    };

    const { error } = await supabase.from("students").insert(data);

    if (error) {
        return { success: false, error: error.message };
    }

    revalidatePath("/dashboard/students");
    return { success: true };
}

export async function updateStudent(id: string, formData: FormData): Promise<ActionState> {
    const supabase = await createClient();
    // id is passed as argument now

    const data = {
        first_name: formData.get("first_name") as string,
        last_name: formData.get("last_name") as string,
        email: formData.get("email") as string,
        phone: formData.get("phone") as string,
        dni: formData.get("dni") as string,
        address: formData.get("address") as string,
        has_license: formData.get("has_license") === 'true',
        disability_observation: formData.get("disability_observation") as string,
        emergency_contact_name: formData.get("emergency_contact_name") as string,
        emergency_contact_phone: formData.get("emergency_contact_phone") as string,
        emergency_contact_relation: formData.get("emergency_contact_relation") as string,
        gender: formData.get("gender") as string,
        status: formData.get("status") as string,
    };

    const { error } = await supabase.from("students").update(data).eq("id", id);

    if (error) {
        return { success: false, error: error.message };
    }

    revalidatePath("/dashboard/students");
    return { success: true };
}

export async function createPackage(formData: FormData): Promise<ActionState> {
    const supabase = await createClient();
    const student_id = formData.get("student_id") as string;

    // VALIDATION: Check if student has active package with credits
    const { count } = await supabase
        .from('student_packages')
        .select('*', { count: 'exact', head: true })
        .eq('student_id', student_id)
        .eq('status', 'active')
        .gt('credits', 0);

    if (count && count > 0) {
        return { success: false, error: 'El estudiante ya tiene un paquete con créditos disponibles. Agote los créditos actuales antes de asignar uno nuevo.' };
    }

    // Assuming a 'packages' or 'student_packages' table. 
    // Using a generic insert structure based on dialog fields.
    const data = {
        student_id,
        name: formData.get("name") as string,
        credits: parseInt(formData.get("credits") as string),
        total_credits: parseInt(formData.get("credits") as string),
        price: parseFloat(formData.get("price") as string),
        // status might be generated by default
    };

    const { error } = await supabase.from("student_packages").insert(data);

    if (error) {
        return { success: false, error: error.message };
    }

    revalidatePath("/dashboard/students");
    return { success: true };
}

export async function deleteStudent(id: string): Promise<ActionState> {
    const supabase = await createClient();

    const { error } = await supabase.from("students").update({ deleted_at: new Date().toISOString() }).eq("id", id);

    if (error) {
        return { success: false, error: error.message };
    }

    revalidatePath("/dashboard/students");
    return { success: true };
}
