export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export type Database = {
    public: {
        Tables: {
            appointment_enrollments: {
                Row: {
                    appointment_id: string
                    attended: boolean | null
                    enrolled_at: string | null
                    id: string
                    student_id: string
                }
                Insert: {
                    appointment_id: string
                    attended?: boolean | null
                    enrolled_at?: string | null
                    id?: string
                    student_id: string
                }
                Update: {
                    appointment_id?: string
                    attended?: boolean | null
                    enrolled_at?: string | null
                    id?: string
                    student_id?: string
                }
            }
            // ... (types truncated for brevity - full types generated by Supabase)
        }
    }
}
